/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emanuel_tonial
 */
public class Tela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        lblIngredientesExtra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbPequena = new javax.swing.JRadioButton();
        rbMedia = new javax.swing.JRadioButton();
        rbGrande = new javax.swing.JRadioButton();
        lblPrecoPequena = new javax.swing.JLabel();
        lblPrecoMedia = new javax.swing.JLabel();
        lblPrecoGrande = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPequena = new javax.swing.JTextField();
        tfMedia = new javax.swing.JTextField();
        tfGrande = new javax.swing.JTextField();
        tfExtras = new javax.swing.JTextField();
        btnConfrimar = new javax.swing.JButton();
        lblTipoPagamento = new javax.swing.JLabel();
        cbTipoPagamento = new javax.swing.JComboBox<>();
        cbBacon = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPizza = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Pedidos");

        jLabel2.setText("Escolha as opçoes de pizza abaixo:");

        lblTamanho.setText("Tamanho");

        lblIngredientesExtra.setText("Ingredientes extras");

        jLabel5.setText("Preços");

        buttonGroup1.add(rbPequena);
        rbPequena.setText("Pequena");

        buttonGroup1.add(rbMedia);
        rbMedia.setText("Media");

        buttonGroup1.add(rbGrande);
        rbGrande.setText("Grande");

        lblPrecoPequena.setText("Pequena:");

        lblPrecoMedia.setText("Media:");

        lblPrecoGrande.setText("Grande:");

        jLabel7.setText("Extras:");

        btnConfrimar.setText("Confirmar Pedido");
        btnConfrimar.addActionListener(this::btnConfrimarActionPerformed);

        lblTipoPagamento.setText("Tipo de Pagamento:");

        cbTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Cartao" }));

        cbBacon.setText("Bacon");

        jCheckBox2.setText("Queijo");

        jCheckBox3.setText("Champignon");

        txaPizza.setColumns(20);
        txaPizza.setRows(5);
        jScrollPane1.setViewportView(txaPizza);

        jPanel1.setBackground(new java.awt.Color(176, 176, 220));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Pedido de Pizza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel3)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoPagamento)
                            .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnConfrimar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbPequena)
                                        .addComponent(rbMedia)
                                        .addComponent(rbGrande)
                                        .addComponent(lblTamanho))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBox2)
                                                .addComponent(jCheckBox3)
                                                .addComponent(cbBacon)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblIngredientesExtra)))
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPrecoMedia)
                                                .addComponent(lblPrecoPequena)
                                                .addComponent(lblPrecoGrande)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfExtras, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                                .addComponent(tfGrande)
                                                .addComponent(tfMedia)
                                                .addComponent(tfPequena)))
                                        .addComponent(jLabel5)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPequena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoPequena))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbGrande)
                                    .addComponent(jCheckBox3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecoMedia)
                                    .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecoGrande)
                                    .addComponent(tfGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(lblTipoPagamento)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnConfrimar)
                                .addGap(107, 107, 107))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTamanho)
                                    .addComponent(lblIngredientesExtra)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbPequena)
                                    .addComponent(cbBacon))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbMedia)
                                    .addComponent(jCheckBox2)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfrimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfrimarActionPerformed
        String tamanho;
    double precoPizza;
 
    if (rbPequena.isSelected()) {
        tamanho = "Pequena";
        precoPizza = lerValor(tfPequena);
    } else if (rbMedia.isSelected()) {
        tamanho = "Média";
        precoPizza = lerValor(tfMedia);
    } else if (rbGrande.isSelected()) {
        tamanho = "Grande";
        precoPizza = lerValor(tfGrande);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Selecione o tamanho da pizza!",
                "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
 
    double precoExtra = lerValor(tfExtras);
    StringBuilder ingredientes = new StringBuilder();
    int qtdExtras = 0;
 
    if (cbBacon.isSelected())    { adicionarIngrediente(ingredientes, "Bacon");      qtdExtras++; }
    if (jCheckBox2.isSelected()) { adicionarIngrediente(ingredientes, "Queijo");     qtdExtras++; }
    if (jCheckBox3.isSelected()) { adicionarIngrediente(ingredientes, "Champignon"); qtdExtras++; }
 
    String textoIngredientes = (qtdExtras == 0) ? "nenhum" : ingredientes.toString();
 
    String pagamento = (String) cbTipoPagamento.getSelectedItem();
 
    double total = precoPizza + (qtdExtras * precoExtra);
 
    StringBuilder sb = new StringBuilder();
    sb.append("Tamanho da pizza: ").append(tamanho).append("\n");
    sb.append("Ingredientes extras: ").append(textoIngredientes).append("\n");
    sb.append("Tipo de Pagamento: ").append(pagamento).append("\n");
    sb.append(String.format("Valor total da pizza: R$ %.2f", total));
 
    txaPizza.setText(sb.toString());

    }//GEN-LAST:event_btnConfrimarActionPerformed

    private double lerValor(javax.swing.JTextField campo) {
        String texto = campo.getText().trim().replace(",", ".");
        if (texto.isEmpty()) {
            return 0.0;
        }
        try {
            return Double.parseDouble(texto);
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }
    
    private void adicionarIngrediente(StringBuilder sb, String nome) {
        if (sb.length() > 0) {
            sb.append(", ");
        }
        sb.append(nome);
    }      


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfrimar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBacon;
    private javax.swing.JComboBox<String> cbTipoPagamento;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIngredientesExtra;
    private javax.swing.JLabel lblPrecoGrande;
    private javax.swing.JLabel lblPrecoMedia;
    private javax.swing.JLabel lblPrecoPequena;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTipoPagamento;
    private javax.swing.JRadioButton rbGrande;
    private javax.swing.JRadioButton rbMedia;
    private javax.swing.JRadioButton rbPequena;
    private javax.swing.JTextField tfExtras;
    private javax.swing.JTextField tfGrande;
    private javax.swing.JTextField tfMedia;
    private javax.swing.JTextField tfPequena;
    private javax.swing.JTextArea txaPizza;
    // End of variables declaration//GEN-END:variables
}
