version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-poo2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
