CREATE DATABASE IF NOT EXISTS aula01;
CREATE DATABASE IF NOT EXISTS aula02;
CREATE DATABASE IF NOT EXISTS aula03;
CREATE DATABASE IF NOT EXISTS aula04;
CREATE DATABASE IF NOT EXISTS aula05;

GRANT ALL PRIVILEGES ON aula01.* TO 'aluno'@'%';
GRANT ALL PRIVILEGES ON aula02.* TO 'aluno'@'%';
GRANT ALL PRIVILEGES ON aula03.* TO 'aluno'@'%';
GRANT ALL PRIVILEGES ON aula04.* TO 'aluno'@'%';
GRANT ALL PRIVILEGES ON aula05.* TO 'aluno'@'%';

FLUSH PRIVILEGES;
